site_name: extratools APIs

repo_name: chuanconggao/extratools
repo_url: https://github.com/chuanconggao/extratools

copyright: "Copyright © Chuancong Gao"

extra:
    social:
        - type: github
          link: https://github.com/chuanconggao

        - type: twitter
          link: https://twitter.com/chuancong

theme:
    name: material
    language: en
    logo: favicon.jpg
    favicon: favicon.jpg

markdown_extensions:
    - admonition
    - codehilite:
        use_pygments: true
        pygments_style: monokai
        noclasses: true
    - footnotes
    - nl2br
    - smarty
    - mdx_math:
        enable_dollar_delimiter: true
    - toc:
        permalink: true

extra_javascript: ["https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML"]

google_analytics: ["UA-119119396-1", "www.chuancong.site"]

pages:
    - Index: index.md

    - Functions:
        - seqtools: functions/seqtools.md
        - sortedtools: functions/sortedtools.md
        - strtools: functions/strtools.md
        - rangetools: functions/rangetools.md
        - dicttools: functions/dicttools.md
        - jsontools: functions/jsontools.md
        - settools: functions/settools.md
        - tabletools: functions/tabletools.md
        - mathtools: functions/mathtools.md
        - stattools: functions/stattools.md
        - misctools: functions/misctools.md
        - printtools: functions/printtools.md
        - debugtools: functions/debugtools.md

    - Data Structures:
        - disjointsets.DisjointSets: datastructures/disjointsets.md
        - defaultlist.DefaultList: datastructures/defaultlist.md
        - segmenttree.SegmentTree: datastructures/segmenttree.md

    - CLI Tools: cli.md
