site_name: extratools APIs

theme: material

pages:
    - Index: index.md
    - Functions:
        - seqtools: functions/seqtools.md
        - sortedtools: functions/sortedtools.md
        - strtools: functions/strtools.md
        - rangetools: functions/rangetools.md
        - dicttools: functions/dicttools.md
        - jsontools: functions/jsontools.md
        - settools: functions/settools.md
        - tabletools: functions/tabletools.md
        - mathtools: functions/mathtools.md
        - stattools: functions/stattools.md
        - misctools: functions/misctools.md
        - printtools: functions/printtools.md
        - debugtools: functions/debugtools.md
    - Data Structures:
        - disjointsets.DisjointSets: datastructures/disjointsets.md
        - defaultlist.DefaultList: datastructures/defaultlist.md
        - segmenttree.SegmentTree: datastructures/segmenttree.md
    - CLI Tools: cli.md

repo_name: "chuanconggao/extratools"
repo_url: "https://github.com/chuanconggao/extratools"
