site_name: extratools APIs

theme: material

pages:
    - Index: index.md
    - Functions: functions.md
    - Data Structures: datastructures.md
    - CLI Tools: cli.md

repo_name: "chuanconggao/extratools"
repo_url: "https://github.com/chuanconggao/extratools"
